# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e227359c6225dffad6d58b21058765e95b6a197f6c36bc155518ce344d43a60238788a3802e0d87dca1892e15c0e389cea2054f656f6627aebb77ef9a292a62

test:
  secret_key_base: c9c62b583d99c9cefe9b3b54648a54e050f6f4fdd08bb828468e72793d20547c0fa406cbfa3149c0139714ddf1a0816bfa7c0d5bc170b9e161cd541d5998098e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
